/**
 * .NET 6.0 WebAPI - Clean Architecture
 * Clean Architecture Template for .NET 6.0 WebApi built with Multitenancy Support.
 *
 * OpenAPI spec version: v2
 * Contact: hello@codewithmukesh.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Filter } from './filter';
import { Search } from './search';

export interface BaseFilter { 
    /**
     * Column Wise Search is Supported.
     */
    advancedSearch?: Search;
    /**
     * Keyword to Search in All the available columns of the Resource.
     */
    keyword?: string;
    /**
     * Advanced column filtering with logical operators and query operators is supported.
     */
    advancedFilter?: Filter;
}