/**
 * .NET 6.0 WebAPI - Clean Architecture
 * Clean Architecture Template for .NET 6.0 WebApi built with Multitenancy Support.
 *
 * OpenAPI spec version: v4
 * Contact: hello@codewithmukesh.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface OrdersDto { 
    id?: string;
    name?: string;
    description?: string;
    quantity?: number;
    percentage?: number;
    price?: number;
    productId?: string;
    productName?: string;
}